#!/bin/bash

function send_notification() {
  volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

volume=$(pamixer --get-volume)
case $1 in
up)
	pamixer -u
  if (($volume > 95)); then
    pamixer --set-volume 100 
  fi
	send_notification $1
	;;
down)
	pamixer -u
	send_notification $1
	;;
mute)
	if $(pamixer --get-mute); then
		dunstify -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
